SELECT COUNT(*) AS CNT -- GROUP 함수
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';

SELECT COUNT(*)
FROM USER
WHERE ID ='HONG'; -- 이런식으로 ID 중복 체크 등에 사용될 수 있다.

SELECT COUNT(*)
FROM ENROL 
WHERE ENR_GRADE >= 80;

SELECT S.STU_NO, STU_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE ENR_GRADE >= 80;

