-- ORDER BY (DEFAULT) 오름차순으로 정렬됨
SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT ;

-- ORDER BY (DESC) 내림차순으로 정렬됨
SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT DESC, STU_NAME;

-- STUDENT, ENROL, SUBJECT
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;


-- ANSI JOIN
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT  S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- ORACLE JOIN > 사실상 사장된 느낌인듯 (LEGACY)
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT  S, ENROL E
WHERE S.STU_NO = E.STU_NO;

-- ENROL TABLE 정보 출력 시, 과목명을 같이 출력
SELECT S.STU_NO, STU_NAME,SUB_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT J ON E.SUB_NO = J.SUB_NO;

SELECT STU_NAME "학생 이름",SUB_NAME "과목명", ENR_GRADE "점수"
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
ORDER BY STU_NAME;

SELECT AVG(ENR_GRADE) ,STU_NO
FROM ENROL 
GROUP BY STU_NO;



SELECT SUB_NO "과목 번호", AVG(ENR_GRADE) 점수
FROM ENROL E
GROUP BY SUB_NO;

SELECT STU_NAME "학생 이름", STU_DEPT 학과, AVG(ENR_GRADE) "평균 점수"
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT
ORDER BY AVG(ENR_GRADE) DESC;

SELECT STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
GROUP BY STU_NO, STU_NAME;

SELECT STU_NO, STU_NAME, ENR_AVG
FROM (
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) ENR_AVG
FROM STUDENT S
INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
GROUP BY S.STU_NO, STU_NAME)
WHERE ENR_AVG > (SELECT AVG(ENR_GRADE) FROM ENROL);

SELECT S.STU_NO, STU_NAME, ENR_AVG
FROM STUDENT S
INNER JOIN (SELECT STU_NO, AVG(ENR_GRADE) ENR_AVG
FROM ENROL
GROUP BY STU_NO) E ON E.STU_NO = S.STU_NO
WHERE ENR_AVG > (SELECT AVG(ENR_GRADE) FROM ENROL);





