SELECT * FROM EMP; -- MGR == 사수(MANAGER) SALGRADE: 급여, COMMISSION: 보너스, DEPTNO: 부서번호
SELECT * FROM DEPT;
SELECT * FROM SALGRADE; -- 급여 등급 SALARY GRADE

-- JOB이 MANAGER인 사람들의 평균 급여

SELECT ROUND(AVG(SAL),1)
FROM EMP
WHERE JOB = 'MANAGER';

-- 사번, 이름, 사수의 이름 (SELF JOIN)
SELECT E.EMPNO, E.ENAME, E2.ENAME
FROM EMP E
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO
;

-- 부하직원의 수 출력

SELECT E.EMPNO, E.ENAME, COUNT(E2.ENAME)
FROM EMP E
LEFT JOIN EMP E2 ON E.EMPNO = E2.MGR
GROUP BY E.EMPNO, E.ENAME
;

SELECT E.ENAME, E.EMPNO, NVL(E2.CNT, 0) AS CNT
FROM EMP E
LEFT JOIN(
    SELECT COUNT(*) AS CNT, MGR
    FROM EMP
    GROUP BY MGR
    ) E2 ON E.EMPNO = E2.MGR;

