
-- 1. STUDENT 테이블에서 기계과 이면서 키가 170 이상인 학생 조회

SELECT * 
FROM STUDENT
WHERE STU_DEPT = '기계' AND STU_HEIGHT >= 170;

SELECT * FROM STUDENT ORDER BY STU_HEIGHT DESC;

-- 2. STUDENT 테이블에서 키가 165~175 사이인 학생 구하기(BETWEEN 사용하기)

SELECT *
FROM STUDENT
WHERE STU_HEIGHT BETWEEN 165 AND 175
ORDER BY STU_HEIGHT DESC;

SELECT * FROM STUDENT ORDER BY STU_HEIGHT DESC;

-- 3. 컴퓨터정보과 학생중 가장 키 큰 학생보다 큰 키를 가진 학생들 구하기

SELECT * 
FROM STUDENT
WHERE STU_HEIGHT > (SELECT MAX(STU_HEIGHT) FROM STUDENT WHERE STU_DEPT = '컴퓨터정보' );

SELECT * FROM STUDENT ORDER BY STU_HEIGHT DESC;


-- 4. 학과별 가장 키가 큰 값(학과명, 키 출력)

SELECT STU_DEPT, MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT * FROM STUDENT ORDER BY STU_HEIGHT DESC;


-- 5. 컴퓨터개론 수업을 듣는 학생의 학번, 이름 출력
SELECT COUNT(*) FROM ENROL;

SELECT S.STU_NO, STU_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_NAME = '컴퓨터개론';

-- 6. 옥한빛의 평균 점수보다 높은 평균 점수를 받은 학생들의 이름, 평균점수 출력

SELECT STU_NAME, ENR_AVG
FROM STUDENT S
INNER JOIN(
    SELECT STU_NO, AVG(ENR_GRADE) AS ENR_AVG 
    FROM ENROL
    GROUP BY STU_NO) E ON S.STU_NO = E.STU_NO
WHERE ENR_AVG > (
    SELECT AVG(ENR_GRADE)
    FROM ENROL E
    INNER JOIN STUDENT S ON S.STU_NO = E.STU_NO
    WHERE STU_NAME = '옥한빛')
ORDER BY ENR_AVG DESC;

SELECT STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
GROUP BY STU_NAME
ORDER BY AVG(ENR_GRADE) DESC;
















