-- SUB QUERY

SELECT *
FROM T_EMP
WHERE PAY = (SELECT MAX(PAY) FROM T_EMP) OR PAY =(SELECT MIN(PAY) FROM T_EMP);

SELECT *
FROM T_EMP
WHERE DEPTNO IN (1001, 1002); -- 둘중 하나인 경우 )(OR)

-- STUDENT 테이블에서 학생들의 전체 평균 키보다 큰 키를 가진 학생들의 목록 출력

SELECT *
FROM STUDENT
WHERE STU_HEIGHT > (SELECT AVG(STU_HEIGHT) FROM STUDENT) AND STU_GRADE = 2;

SELECT AVG(STU_HEIGHT)
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_WEIGHT < (SELECT AVG(STU_WEIGHT) FROM STUDENT);

SELECT AVG(STU_WEIGHT)
FROM STUDENT;