CREATE TABLE TBL_BOARD (
    BOARDNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR2(1000),
    USERID VARCHAR2(20),
    HIT NUMBER,
    CATEGORY NUMBER CHECK (CATEGORY IN (1, 2, 3)),
    FAVORITE NUMBER,
    TAG1 VARCHAR2(20),
    TAG2 VARCHAR2(20),
    NOTICEYN VARCHAR2(1) CHECK (NOTICEYN IN ('Y', 'N')),
    CDATETIME DATE,
    UDATETIME DATE
);

CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1;

-- 샘플 데이터 삽입
INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '첫 번째 글', '첫 번째 글의 내용입니다.', 'user1', 100, 1, 10, 'tag1', 'tag2', 'N', SYSDATE, SYSDATE);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '두 번째 글', '두 번째 글의 내용입니다.', 'user2', 50, 2, 5, 'tag2', 'tag3', 'N', SYSDATE - 1, SYSDATE - 1);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '중요 공지사항', '오늘부터 중요한 공지사항입니다.', 'admin', 200, 1, 20, 'notice', NULL, 'Y', SYSDATE - 2, SYSDATE - 1);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '자유게시판 글', '자유롭게 이야기 나누는 게시판입니다.', 'user3', 80, 2, 15, 'free', 'discussion', 'N', SYSDATE - 3, SYSDATE - 2);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '문의사항', '질문이 있습니다.', 'user4', 30, 3, 3, 'question', NULL, 'N', SYSDATE - 4, SYSDATE - 3);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '게시글 제목', '게시글 내용입니다.', 'user5', 40, 2, 8, 'tag5', 'tag6', 'N', SYSDATE - 5, SYSDATE - 4);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '공지사항 제목', '오늘의 공지사항입니다.', 'admin', 150, 1, 12, 'announcement', NULL, 'Y', SYSDATE - 6, SYSDATE - 5);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '오늘의 글', '오늘의 이야기를 나누는 곳입니다.', 'user6', 60, 2, 7, 'today', 'story', 'N', SYSDATE - 7, SYSDATE - 6);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '질문 글', '질문이 있습니다.', 'user7', 25, 3, 2, 'question', NULL, 'N', SYSDATE - 8, SYSDATE - 7);

INSERT INTO TBL_BOARD (BOARDNO, TITLE, CONTENTS, USERID, HIT, CATEGORY, FAVORITE, TAG1, TAG2, NOTICEYN, CDATETIME, UDATETIME)
VALUES (board_seq.nextval, '여덟 번째 글', '여덟 번째 글의 내용입니다.', 'user8', 35, 2, 4, 'tag8', 'tag9', 'N', SYSDATE - 9, SYSDATE - 8);

COMMIT;


CREATE SEQUENCE comment_seq
START WITH 1
INCREMENT BY 1;

-- 테이블 생성
CREATE TABLE TBL_COMMENT (
    COMMENTNO NUMBER PRIMARY KEY,
    BOARDNO NUMBER,
    CONTENTS VARCHAR2(200),
    USERID VARCHAR2(20),
    FAVORITE NUMBER,
    PCOMMENTNO NUMBER,
    CDATETIME DATE,
    UDATETIME DATE
);


-- 샘플 데이터 삽입
INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 1, '첫 번째 댓글입니다.', 'user1', 5, NULL, SYSDATE, SYSDATE);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 1, '두 번째 댓글입니다.', 'user2', 3, NULL, SYSDATE - 1, SYSDATE - 1);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 2, '댓글 내용입니다.', 'user3', 2, NULL, SYSDATE - 2, SYSDATE - 1);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 3, '좋은 글이네요.', 'user4', 7, 1, SYSDATE - 3, SYSDATE - 2);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 3, '고마워요.', 'user5', 1, NULL, SYSDATE - 4, SYSDATE - 3);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 4, '댓글입니다.', 'user6', 4, NULL, SYSDATE - 5, SYSDATE - 4);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 5, '정말 유용한 정보네요.', 'user7', 10, NULL, SYSDATE - 6, SYSDATE - 5);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 5, '추가 질문이 있습니다.', 'user8', 3, NULL, SYSDATE - 7, SYSDATE - 6);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 6, '동의합니다.', 'user9', 6, 2, SYSDATE - 8, SYSDATE - 7);

INSERT INTO TBL_COMMENT (COMMENTNO, BOARDNO, CONTENTS, USERID, FAVORITE, PCOMMENTNO, CDATETIME, UDATETIME)
VALUES (comment_seq.nextval, 6, '다른 의견도 듣고 싶습니다.', 'user10', 2, 2, SYSDATE - 9, SYSDATE - 8);

COMMIT;


CREATE TABLE TBL_BOARDFILE (
    FILENO NUMBER PRIMARY KEY,
    BOARDNO NUMBER,
    FILENAME VARCHAR2(50),
    FILEORGNAME VARCHAR2(50),
    FILEPATH VARCHAR2(200),
    FILESIZE NUMBER,
    FILEEXT VARCHAR2(10),
    THUMBNAILYN VARCHAR2(1)
);
CREATE SEQUENCE boardfile_seq
START WITH 1
INCREMENT BY 1;

commit;