-- TRIGGER
-- 변수 선언 시 IS가 아닌 DECLARE 사용
CREATE OR REPLACE TRIGGER TRIGGER_TEST1
    BEFORE -- AFTER 이벤트 발생 전후, 트리거 호출 시점을 고를 수 있다.
    UPDATE ON DEPT    -- 이벤트 지정 OR INSERT 이런식으로 여러개의 이벤트 지정도 가능
    FOR EACH ROW     -- RECORD 하나당 한번씩 실행. 옵션이 없다면 업데이트 1회 시 한번만 호출된다.
BEGIN
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :OLD.DNAME);
    DBMS_OUTPUT.PUT_LINE('변경 후 : ' || :NEW.DNAME);
END;
/

SELECT * FROM DEPT;
UPDATE DEPT
SET DNAME = 'TEST'
WHERE DEPTNO = 10;

CREATE OR REPLACE TRIGGER TRG_TEST
    AFTER 
    INSERT ON EMP
    FOR EACH ROW
DECLARE 
    RETURN_AVG NUMBER;
BEGIN
    SELECT ROUND(AVG(SAL))
    INTO RETURN_AVG
    FROM EMP;
    DBMS_OUTPUT.PUT_LINE('급여 평균 : ' || RETURN_AVG);
END;
/

DELETE FROM EMP WHERE ENAME = 'TEST';
SELECT * FROM EMP;
SELECT ROUND(AVG(SAL))
    FROM EMP;
    
INSERT INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL)
    VALUES(100, 'TEST', 'SALES', SYSDATE, 1234);
    
ROLLBACK;

CREATE OR REPLACE TRIGGER TRG_TEST1
	BEFORE
	UPDATE ON EMP
	FOR EACH ROW
DECLARE
	SAL_INCREASE NUMBER;
BEGIN
	SAL_INCREASE := :NEW.SAL - :OLD.SAL;
	DBMS_OUTPUT.PUT_LINE('이전 값 : ' || :OLD.SAL);
	DBMS_OUTPUT.PUT_LINE('바뀐 값 : ' || :NEW.SAL);
	DBMS_OUTPUT.PUT_LINE('증가 값 : ' || SAL_INCREASE);
	INSERT INTO TBL_SAL_INCREASE
	VALUES(EMPNO = EMP.EMPNO , INCREASE = SAL_INCREASE);
END;
/
