DROP TABLE STUDENT_LOG;

CREATE TABLE STUDENT_LOG(
    L_STUNO VARCHAR(8),
    L_STUNAME VARCHAR2(12),
    L_STUDEPT VARCHAR2(20),
    L_DATE DATE,
    L_ID VARCHAR2(40),
    L_EVENT VARCHAR(10));

CREATE OR REPLACE TRIGGER TRG_STUDENT
    AFTER
    UPDATE OR INSERT OR DELETE ON STUDENT
    FOR EACH ROW
BEGIN
    IF INSERTING THEN 
    INSERT INTO STUDENT_LOG
    VALUES(:NEW.STU_NO, :NEW.STU_NAME, :NEW.STU_DEPT, SYSDATE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I');
    ELSIF UPDATING THEN 
    INSERT INTO STUDENT_LOG
    VALUES(:NEW.STU_NO, :NEW.STU_NAME, :NEW.STU_DEPT, SYSDATE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U');
    ELSIF DELETING THEN 
    INSERT INTO STUDENT_LOG
    VALUES(:OLD.STU_NO, :OLD.STU_NAME, :OLD.STU_DEPT, SYSDATE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'D');
    END IF;
END;
/

SELECT * FROM STUDENT;
INSERT INTO STUDENT(STU_NO,STU_NAME)
    VALUES (11111111, '±Ë«—∫∞');
UPDATE STUDENT
    SET STU_NAME = '±Ë±Ë±Ë'
    WHERE STU_NAME = '±Ë«—∫∞';
DELETE FROM STUDENT WHERE STU_NAME = '±Ë±Ë±Ë';


SELECT * FROM STUDENT_LOG;
TRUNCATE TABLE STUDENT_LOG;
DROP TABLE STUDENT_LOG;
