SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

-- 사원명, 직급, 부서명, 부서위치를 출력
SELECT ENAME, JOB,DNAME, LOC
FROM EMP E
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO;

-- 사원번호, 사원명, 급여, 급여등급을 출력 INNER JOIN 'COLUMN' ON 'BOOLEAN' 이라고 보면 될듯?
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL;

-- 각 직급(JOB) 별 급여평균등급 
SELECT JOB, ROUND(AVG(GRADE), 1)
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
GROUP BY JOB;

-- 부서별 급여평균등급(부서명, 부서등급 출력)
SELECT DNAME, ROUND(AVG(GRADE), 1)
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME;

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

-- 1. 2000이상 급여를 받는 사람의 수를 구하시오.
SELECT COUNT(*)
FROM EMP
WHERE SAL >= 2000;

-- 2. 사원번호, 이름, 급여를 출력하시오. 단, 급여를 출력할 때, 
--    커미션을 받는 사람은 커미션과 더해서 출력할 것.
SELECT EMPNO, ENAME, SAL + NVL(COMM, 0) AS 급여
FROM EMP;

-- 3. WARD보다 많은 급여(SAL)을 받는 사람들을 출력하시오.
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
FROM EMP
WHERE ENAME ='WARD');

-- 4. 급여등급이 3등급 이상인 사람들의 수를 출력하시오.
SELECT COUNT(*)
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
WHERE GRADE >= 3;

-- 5. 81년도에 입사한 사람들을 모두 출력하시오.
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YY') = 81;

-- 6. 각 직급별 가장 많은 급여를 받는 사람을 출력하시오.
SELECT E.*
FROM EMP E
INNER JOIN(
            SELECT MAX(SAL) AS MAX_SAL, JOB
            FROM EMP
            GROUP BY JOB) E2 ON E.SAL = E2.MAX_SAL AND E.JOB = E2.JOB;
            
-- WHERE에서 저런 양식으로도 넣을 수 있다함(잘안씀)
SELECT *
FROM EMP E
WHERE (SAL, JOB) IN (SELECT MAX(SAL) AS MAX_SAL, JOB
            FROM EMP
            GROUP BY JOB);

-- 7. SALESMAN 직급보다 평균급여가 높은 부서들의 부서명, 평균 급여 등급을 출력하시오.
SELECT DNAME, ROUND(AVG(GRADE), 1)
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON D.DEPTNO = E.DEPTNO
GROUP BY DNAME
HAVING ROUND(AVG(SAL)) > (SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'SALESMAN');

-- ROUND 음수 값 찾기
SELECT ROUND(AVG(SAL),-3),AVG(SAL)
FROM EMP
GROUP BY DEPTNO;