CREATE OR REPLACE TRIGGER TRG_EMP
    AFTER
    UPDATE OR INSERT OR DELETE ON EMP
    FOR EACH ROW
BEGIN
    IF UPDATING THEN
        INSERT INTO EMP_LOG
            VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U');
    ELSIF INSERTING THEN
        INSERT INTO EMP_LOG
            VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I');
    ELSIF DELETING THEN
        INSERT INTO EMP_LOG
            VALUES (:OLD.EMPNO, :OLD.MGR, :OLD.SAL, :OLD.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'D');
--        RAISE_APPLICATION_ERROR(-20000,'EMP 테이블은 삭제 불가');
        -- 사용자 정의 에러
        -- -20000 ~ -29999까지 오류번호 사용 가능.
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMP2
    BEFORE
    DELETE ON EMP
    FOR EACH ROW
BEGIN
    IF UPPER(TO_CHAR(SYSDATE,'DY')) IN ('수', '토', '일') THEN
    RAISE_APPLICATION_ERROR(-20001, '주말엔 데이터 삭제가 불가능합니다.');
    END IF;
END;
/

SELECT * FROM EMP;

INSERT INTO EMP
    VALUES(1111,'NAME','JOB', 7369, '11/11/11', 400, 400, 10);
UPDATE EMP
    SET SAL = SAL+100
    WHERE ENAME = 'NAME';
DELETE FROM EMP
    WHERE ENAME = 'NAME';