-- PARAMETER 테이블 타입 참조

CREATE OR REPLACE PROCEDURE SET_GRADE
    (P_STU_NO IN ENROL.STU_NO%TYPE, 
    P_SUB_NO IN ENROL.SUB_NO%TYPE,  
    P_ENR_GRADE IN ENROL.ENR_GRADE%TYPE) 
IS
    P_COUNT NUMBER;
BEGIN
    DBMS_OUTPUT.ENABLE;
    
    UPDATE ENROL
    SET ENR_GRADE = ENR_GRADE + P_ENR_GRADE
    WHERE SUB_NO = P_SUB_NO AND STU_NO = P_STU_NO;
    
    P_COUNT := SQL%ROWCOUNT;
    
    IF P_COUNT =0 THEN
        DBMS_OUTPUT.PUT_LINE('해당 학번이나 과목이 존재하지 않습니다.');
    ELSE 
        DBMS_OUTPUT.PUT_LINE(P_COUNT ||'개 행이 저장되었습니다.');
    END IF;
    COMMIT;
END;
/

SET SERVEROUTPUT ON;
SELECT * FROM ENROL;

EXECUTE SET_GRADE(20131001, 101, 5);