CREATE TABLE BOOK_LOG(
    BOOKID_L NUMBER,
    OLD_PRICE NUMBER,
    NEW_PRICE NUMBER,
    CDATETIME DATE,
    ID VARCHAR2(40)
);

COMMIT;

CREATE OR REPLACE TRIGGER BOOK_TRIGGER
    AFTER
    UPDATE ON BOOK
    FOR EACH ROW
BEGIN
    INSERT INTO BOOK_LOG
    VALUES(:OLD.BOOKID, :OLD.PRICE, :NEW.PRICE, SYSDATE, SYS_CONTEXT('USERENV', 'SESSION_USER')); -- ORACLE 툴에 로그인한 계정 정보를 담는다.SYS_CONTEXT('USERENV', 'SESSION_USER')
END;
/

SELECT * FROM BOOK;

UPDATE BOOK
SET PRICE = 8000
WHERE BOOKID =1;

SELECT * FROM BOOK_LOG;

