SELECT * FROM EMP;
-- UNION, UNION ALL
-- COLUMN의 개수는 동일해야하며, 순서(타입) 역시 동일해야한다.

SELECT 
    ENAME, JOB, SAL+NVL(COMM,0) AS SAL_COMM
FROM EMP
WHERE SAL >= 1500
UNION ALL
SELECT 
    ENAME, JOB, SAL+NVL(COMM,0)
FROM EMP
WHERE COMM IS NOT NULL;


SELECT * FROM STUDENT;
SELECT * FROM ENROL;


SELECT 이름, 평균점수
FROM (
    SELECT 
        STU_NAME 이름,
        NVL(AVG(ENR_GRADE),0) 평균점수
        ,1 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON E.STU_NO = S.STU_NO
    GROUP BY STU_NAME, 1
    UNION 
    SELECT 
        '전체평균',
        ROUND(AVG(ENR_GRADE),1)
        , 2 AS ORDERKEY
    FROM ENROL
    
    ORDER BY ORDERKEY, 평균점수 DESC
);