SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
SELECT * FROM STU;

SELECT *
FROM DEPARTMENT D
INNER JOIN DEPARTMENT D2 ON D.PART = D2.DEPTNO
         INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DEPTNO = 10;

-- 공과대학에 속한 (전공이 공과대학인) 학생의 목록을 출력하세요.
SELECT S.STUNO, S.NAME,D.DNAME 학과, D1.DNAME 학부,D2.DNAME 대학분류
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
INNER JOIN DEPARTMENT D1 ON D.PART = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
WHERE D2.DNAME = '공과대학';

-- 인문대학에 속한 교수의 수를 구하시오
SELECT COUNT(*)
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
INNER JOIN DEPARTMENT D1 ON D.PART = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
WHERE D2.DNAME = '인문대학';

-- JUMIN 컬럼을 이용해서 남자 OR 여자인지 판별
SELECT NAME, SUBSTR(JUMIN,7), CASE 
                        WHEN SUBSTR(JUMIN,7,1) IN(1,3) THEN '남자'
                        ELSE '여자'
                    END AS GENDER
FROM STU
ORDER BY GENDER;

