SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT 부서명, 평균금액
FROM (
    SELECT DNAME 부서명, ROUND(AVG(SAL)) 평균금액, 1 AS PRIORITY
    FROM EMP E
    LEFT JOIN DEPT D ON D.DEPTNO = E.DEPTNO
    GROUP BY DNAME
    UNION
    SELECT '전체 평균', ROUND(AVG(SAL)), 2 AS PRIORITY
    FROM EMP
    ORDER BY PRIORITY, 평균금액
);

SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM ENROL;

SELECT 학과, 점수
FROM (
    SELECT SUB_DEPT AS 학과, AVG(ENR_GRADE) AS 점수, 1 PRIORITY
    FROM SUBJECT S
    INNER JOIN ENROL E ON S.SUB_NO = E.SUB_NO
    GROUP BY SUB_DEPT
    UNION
    SELECT '전체평균', ROUND(AVG(ENR_GRADE),1), 2 PRIORITY
    FROM ENROL
    ORDER BY PRIORITY, 점수 DESC
);
