-- FUNCTION
-- 숫자를 넣으면 2배로 리턴해주는 함수
CREATE OR REPLACE FUNCTION SAL_MULTI(P_VALUE NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN P_VALUE*2;
END;
/

SELECT SAL_MULTI(13)
FROM DUAL;

SELECT SAL, SAL_MULTI(SAL) 급여가두배
FROM EMP;

-- 2024-07-17 09:38:30 
CREATE OR REPLACE FUNCTION FORMAT_DATE(CDATE DATE, NUMB NUMBER)
RETURN CHAR
IS
BEGIN
    IF NUMB = 0 THEN
    RETURN TO_CHAR(CDATE, 'YYYY-MM-DD HH24:MI:SS');
    ELSIF NUMB = 1 THEN
    RETURN TO_CHAR(CDATE, 'YYYY.MM.DD HH24:MI:SS');
    ELSIF NUMB = 2 THEN
    RETURN TO_CHAR(CDATE, 'YYMMDD');
    ELSIF NUMB = 3 THEN
    RETURN TO_CHAR(CDATE, 'YYYY-MM-DD HH24:MI:SS DAY');
    ELSE
    RETURN TO_CHAR(CDATE, 'YYYY-MM-DD HH24:MI:SS AM');
    END IF;
END;
/
SELECT * FROM STU;
SELECT FORMAT_DATE(HIREDATE,0) AS HIREDATE
FROM EMP;







