SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;
SELECT * FROM TBL_BOARDFILE;

SELECT B.*, C.*
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
WHERE B.BOARDNO =1;

SELECT COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
WHERE C.BOARDNO =1;

SELECT B.BOARDNO, B.TITLE, B.CONTENTS, NVL(CNT, 0)
FROM TBL_BOARD B
LEFT JOIN (
    SELECT BOARDNO, COUNT(*) CNT
    FROM TBL_COMMENT
    GROUP BY BOARDNO
) C ON B.BOARDNO = C.BOARDNO
ORDER BY B.BOARDNO;
    
SELECT S.STUNO, S.NAME, S.GRADE, NVL(SUM(J.CNT),0)
FROM STU S
LEFT JOIN(
    SELECT COUNT(*) CNT, GRADE
    FROM STU 
    GROUP BY GRADE
) J ON S.GRADE < J.GRADE
GROUP BY S.STUNO, S.NAME, S.GRADE;

SELECT COUNT(S2.GRADE), S1.STUNO, S1.GRADE, S1.NAME
FROM STU S1
LEFT JOIN STU S2 ON S1.GRADE < S2.GRADE
GROUP BY S1.STUNO, S1.GRADE, S1.NAME;

