SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

SELECT * 
FROM EMP E
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO
WHERE E.EMPNO = 7369;

-- 사번, 이름, 직급, 사수의 이름 출력
SELECT E.EMPNO, E.JOB, E.ENAME,E.MGR, E2.ENAME, E2.EMPNO
FROM EMP E
INNER JOIN EMP E2 ON E.MGR = E2.EMPNO;
